dist: trusty
sudo: require

language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - valgrind

install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g wio --unsafe-perm
  - sudo apt-get install -qq gcc-avr avr-libc avrdude -y

script:
  - gcc -v
  - g++ -v
  - cmake --version
  - wio update pkg .
  - wio pac get
  - ./wmake test
  - cd cmake-build-debug
  - valgrind --leak-check=yes ./unit
  - cd ..
  - wio build

